spring:
  application:
    name: spendev-gateway-ms
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: spendev-users-ms
          uri: lb://spendev-users-ms
          predicates:
            - Path=/users/**
        - id: openapi
          uri: lb://spendev-gateway-ms
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/api-docs
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance: ${spring.application.name}:${spring.application.instance_id:${random.value}}